name: hat
channels:
  - conda-forge
dependencies:
  - python
  - eccodes
  - cfgrib
  - cftime
  - geopandas
  - xarray
  - plotly
  - matplotlib
  - jupyterlab
  - netCDF4
  - tqdm
  - ipywidgets
  - typer
  - rich
  - humanize
  - folium
  - typeguard
  - nbstripout
  - nbdime
  - shellingham
  - pip
  - pytest
  - mkdocs
  - black
  - flake8
  - isort
  - pre-commit
  - pip:
     - earthkit.data
