name: hat
channels:
  - conda-forge
dependencies:
  - python=3.10
  - netCDF4
  - eccodes
  - cfgrib
  - cftime
  - geopandas
  - xarray
  - plotly
  - matplotlib
  - jupyterlab
  - tqdm
  - typer
  - humanize
  - folium
  - typer
  - pip
  # - pytest
  # - mkdocs
  # - black
  # - flake8
  # - isort
  # - pre-commit
  - pip:
     - earthkit.data
