name: hat
channels:
  - conda-forge
dependencies:
  - python<=3.10
  - netCDF4
  - eccodes
  - cfgrib
  - geopandas
  - xarray
  - plotly
  - matplotlib
  - jupyter
  - tqdm
  - typer
  - humanize
  - ipyleaflet
  - ipywidgets
  - pip
  - pytest
  - mkdocs
  - black
  - flake8
  - isort
  - pre-commit
  - geopy
  - pandas
  - pip:
     - earthkit.data
