# # i.e. to enable cleaner imports..
# # from hat import read_config, extract_simulations, read_observations
# from hat.config import read_config
# from hat.extract_simulations import extract_simulations
# from hat.read_observations import read_observations

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = ""